plugins { id "com.android.application" }

android {
    namespace "com.zerafix.telaestica"
    compileSdk 35
    defaultConfig {
        applicationId "com.zerafix.telaestica"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}
